dependencies {
  api(libs.netty)
  api(libs.config.lib.yaml)
  api(libs.slf4j.api)
  implementation(project(":common"))

  testImplementation(libs.bundles.netty)
  testImplementation(libs.config.lib.yaml)
  testImplementation(libs.slf4j.api)
  testImplementation(libs.guice)
  testImplementation(libs.guice.assistedinject)
  testImplementation(libs.jzlib)
  testImplementation(libs.slf4j.api)
  testImplementation(libs.log4j.core)
  testImplementation(libs.log4j.slf4j.impl)
  testImplementation(libs.bouncy.castle.pkix)
  testImplementation(project(":common"))
  testImplementation(libs.bouncy.castle.pkix)
  testImplementation(libs.netty.tcnative.boringssl.static)
  testImplementation("${libs.netty.tcnative.boringssl.static.get().module}:${libs.netty.tcnative.boringssl.static.get().version}:windows-x86_64")
  testImplementation("${libs.netty.tcnative.boringssl.static.get().module}:${libs.netty.tcnative.boringssl.static.get().version}:linux-x86_64")
  testImplementation("${libs.netty.tcnative.boringssl.static.get().module}:${libs.netty.tcnative.boringssl.static.get().version}:linux-aarch_64")
  testImplementation("${libs.netty.tcnative.boringssl.static.get().module}:${libs.netty.tcnative.boringssl.static.get().version}:osx-x86_64")
  testImplementation("${libs.netty.tcnative.boringssl.static.get().module}:${libs.netty.tcnative.boringssl.static.get().version}:osx-aarch_64")
}